### ISSUE TITLE
`in` operator not usable in `if`.

### ISSUE THREAD

**Issue by AlexMax** [mozilla/nunjucks#660]
On the subject of `if`, the documentation says:

> It behaves exactly as javascript's if behaves.

However, in converting some swig templates over, I found that they were failing whenever the template made use of the `in` operator.  A failing test is contained in #659.  Here is a backtrace for the failing test:

```
  Template render error: (unknown path)
    TypeError: runtime.contextOrFrameLookup(...).indexOf is not a function
      at Object.exports.prettifyError (src/lib.js:9:1149)
      at src/environment.js:9:23995
      at root [as rootRenderFunc] (eval at <anonymous> (src/environment.js:9:27$78), <anonymous>:19:3)
      at Obj.extend.render (src/environment.js:9:23652)
      at render (tests/util.js:98:22)
      at equal (tests/util.js:36:19)
      at Context.<anonymous> (tests/compiler.js:130:13)
```

**Comment by carljm** [comment]
Pretty sure `if in` works fine with arrays, it just doesn't support objects. It should, though; thanks for the report and failing test!

**Comment by carljm** [comment]
Closed with merge of #661 - thanks @oyyd !
